// Copyright (c) 2020 Microsoft Corporation.
// Licensed under the MIT License.

// This file is autogenerated - do not commit manual changes.

#pragma once

#define UXTOOLSEXAMPLES_COMMIT_SHA "2a1c13a734dae08e7e68939c876a630e41bfd7a0"
